//USER TYPES

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const GET_CURRENTUSER_REQUEST = 'GET_CURRENTUSER_REQUEST';
export const GET_CURRENTUSER_SUCCESS = 'GET_CURRENTUSER_SUCCESS';
export const GET_CURRENTUSER_FAIL = 'GET_CURRENTUSER_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';


//CATEGORY TYPES

export const GET_CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_REQUEST';
export const GET_CATEGORY_FAIL = 'GET_CATEGORY_FAIL';

export const ADD_CATEGORY_REQUEST = 'ADD_CATEGORY_REQUEST';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_REQUEST';
export const ADD_CATEGORY_FAIL = 'ADD_CATEGORY_FAIL';

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL';


//EVENT TYPES

export const GET_EVENT_REQUEST = 'GET_EVENT_REQUEST'
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS'
export const GET_EVENT_FAIL = 'GET_EVENT_FAIL'

export const CREATE_EVENT_REQUEST = 'CREATE_EVENT_REQUEST'
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS'
export const CREATE_EVENT_FAIL = 'CREATE_EVENT_FAIL'

export const GET_EVENTBYID_REQUEST = 'GET_EVENTBYID_REQUEST'
export const GET_EVENTBYID_SUCCESS = 'GET_EVENTBYID_SUCCESS'
export const GET_EVENTBYID_FAIL = 'GET_EVENTBYID_FAIL'

export const REGISTER_EVENT_REQUEST = "REGISTER_EVENT_REQUEST"
export const REGISTER_EVENT_SUCCESS = "REGISTER_EVENT_SUCCESS"
export const REGISTER_EVENT_FAIL = "REGISTER_EVENT_FAIL"

export const GET_MYREGEVENT_REQUEST = "GET_MYREGEVENT_REQUEST"
export const GET_MYREGEVENT_SUCCESS = "GET_MYREGEVENT_SUCCESS"
export const GET_MYREGEVENT_FAIL = "GET_MYREGEVENT_FAIL"

export const GET_MYORGEVENT_REQUEST = "GET_MYORGEVENT_REQUEST"
export const GET_MYORGEVENT_SUCCESS = "GET_MYORGEVENT_SUCCESS"
export const GET_MYORGEVENT_FAIL = "GET_MYORGEVENT_FAIL"


//ZOOM TYPES

export const HANDLE_ZOOMSTART_REQUEST = "HANDLE_ZOOMSTART_REQUEST"
export const HANDLE_ZOOMSTART_SUCCESS = "HANDLE_ZOOMSTART_SUCCESS"
export const HANDLE_ZOOMSTART_FAIL = "HANDLE_ZOOMSTART_FAIL"

export const HANDLE_ZOOMEND_REQUEST = "HANDLE_ZOOMEND_REQUEST"
export const HANDLE_ZOOMEND_SUCCESS = "HANDLE_ZOOMEND_SUCCESS"
export const HANDLE_ZOOMEND_FAIL = "HANDLE_ZOOMEND_FAIL"


export const GET_EVENTBYCATID_REQUEST = "GET_EVENTBYCATID_REQUEST"
export const GET_EVENTBYCATID_SUCCESS = "GET_EVENTBYCATID_SUCCESS"
export const GET_EVENTBYID_CATFAIL = "GET_EVENTBYID_CATFAIL"